apiVersion: 1

datasources:
  - name: OpenTSDB
    type: opentsdb
    access: proxy
    url: http://opentsdb-{{ name }}:4242
    isDefault: true
    jsonData:
      tsdbResolution: 1
      tsdbVersion: 1

  # - name: InfluxDB
  #   type: influxdb
  #   access: proxy
  #   url: http://influxdb:8086
  #   isDefault: false
  #   jsonData:
  #     version: Flux
  #     organization: vlinnik
  #     defaultBucket: default_bucket
  #     tlsSkipVerify: true
  #   secureJsonData:
  #     token: influxdb_admin_token_2025